### PR TITLE
[WIP] Fx layout

### PR DESCRIPTION
**Pull request by Lorsbyjm**
see issue: #124 

### Visible/Frontend Changes
- [x] side menue hidden on smaller screens
- [x] responsive EntitySubrecordComponent (hides columns based on screen size): #197/#198
- [x] ASER Table to large while creating a new entry
- [x] use drop downs for filter panel in smallest screens
- [x] edditing in entity-subrecord is in line, bad on small screen, cause the lines get larger
- [x] Bug on branch fx-layout (resize dashboard) #196
- [x] Filter Panel on school list page
- [x] add space at the bottom of scrollable content, so all gets displayed (see school details)
- [x] Notes popup: Hard to see that note text is scrollable, should be larger/easier to read.
- [ ] attendance manager table ?? Discuss
- [x] allow to remove side navigation in landscape mode
- [x] organge header (logout button outside screen)
- [x] sideNavButton not shown on ipad landscape modus
-------

- [ ] Test the full app for usability on smartphone (or with Chrome's dev tools viewing at different resolutions) and merge this PR

### CODE REVIEW

**Comment by sleidig** [comment]
How about merging this PR as soon as possible and breaking down the remaining tasks into smaller, faster PRs to avoid complicated merge conflicts?

**Comment by Lorsbyjm** [comment]
Sure, but then it looks ugly and has some failures.

**Comment by Lorsbyjm** [comment]
@sleidig Should it be able to create new table entries with the smartphone version? If not, we could just disable the functionality and maybe add it later.

**Comment by sleidig** [comment]
I think it's reasonable to limit the (responsive) features on small screens - mostly to reading data. Probably most people prefer adding stuff with a larger screen and proper keyboard anyway.

**Comment by Lorsbyjm** [comment]
ok, thats good. Some failures could be solved by just unableing editing in the entity-subrecord component. But for the future it would be nice to solve these issues. I will open another issue.

**Comment by sleidig** [comment]
Awesome that this is nearing completion :-)

Can someone else check through the UI? Things keep piling up on my desk and I don't want to delay this PR. I fully trust your judgements.

**Pull request merged**
