### PR TITLE
fix(*): correctly allow date ranges where start date is in future

### PR DESCRIPTION
**Pull request by sleidig**
allow date ranges where start date is in future and no end date is set

:warning: mark commit for @codo-mentoring

### CODE REVIEW

**Review by TheSlimvReal — COMMENTED** [review]
I am not sure that I can reproduce the bug. When I use the latest master, I can also enter or select a date range in the future.

**Comment by sleidig** [comment]
hmm, interesting. In the demo I can't reproduce either @TheSlimvReal . But here and in a client system it is happening: https://qm.aam-digital.com/matching  (maybe due to synced mode or because the "end" field is not part of the form?)

**Comment by TheSlimvReal** [comment]
@sleidig I think you can reproduce it in the demo. The actual fix to the problem has not yet been deployed (#1988) With the "All" filter option it is also possible to only have a start or end date.

**Comment by sleidig** [comment]
@TheSlimvReal , indeed this bug only occurs if the "end" field is not part of the confirmation popup of the matching view.

**Comment by TheSlimvReal** [comment]
It seems like moment has a different behaviour depending on whether `undefined` or `null` is passed as end date.

**Comment by sleidig** [comment]
> It seems like moment has a different behaviour depending on whether `undefined` or `null` is passed as end date.

ah, that makes sense, I guess.
I'd suggest to go ahead with this PR though, as the fix makes the behavior more explicit and reliable instead of using a not very well known default of moment.js

**Pull request merged**
