### PR TITLE
[WIP] Previous schools

### PR DESCRIPTION
**Pull request by Schottkyc137**
see issue: #398 

### Visible/Frontend Changes
- [x] The "Previous Schools tab" in the "Education" section of a child displays grade and the class
- [x] The Edit-Form can be used to edit those new values (grade and class)

### Architectural/Backend Changes
- [x] The "Edit School Dialog component" now uses the Abstract Details component

### CODE REVIEW

**Comment by codingfabi** [comment]
Is this still WIP? Looks done to me...

**Comment by Schottkyc137** [comment]
I still have some things to fix since this commit uses an outdated version of master

**Comment by sleidig** [comment]
@Schottkyc137 Ideally make PRs against the master for each change that can somehow stand on its own. That makes it much easier to review and quickly merge those parts of you changes that are done instead of collecting a large, long opened PR

**Comment by christophscheuing** [comment]
I'm confused about how we are supposed to handle the attended school class with respect to the time spent at a certain school: If the period of time spent at a given school extends over several classes, should this school classes be mentioned consequently (with separating commas?) in the school class field? Or should there be a different entry for every school class / year, meaning that the period from the start to the end date cannot be longer than one school year?

The way we handle school classes is of importance for issue #317 on how to determine the currently attended school class.

**Comment by sleidig** [comment]
I had one line/entry per school year in mind. That way it should be much easier to manage information about a particular class like the results for that year, etc.  And even if a student should repeat the same class, that becomes more obvious if there are two lines, one for each year, for this.

I didn't think about the constraint, that the form should only allow one year periods, but I agree with you. (although maybe there could also be some kind of training programmes that last 1.5 years? That would make the case to just leave it up to users how they want to use it)

**Pull request merged**
