### PR TITLE
optimized searchbar: only words, removed bug in parse rows

### PR DESCRIPTION
**Pull request by Lorsbyjm**
see issue: #366 

### Visible/Frontend Changes
- [x] searchbar dissapers when searchfield is empty
- [x] searching does not take that long

- please check the regex expression, it should allow only strings with at least one characters or number
- remeber: 
Search depends on pouchdb indices so this can only be debugged when setting useTemporaryDatabase to false in the config.json

### CODE REVIEW

**Comment by sleidig** [comment]
I noticed here that the previous merge in the master of the ChildPhotoService had broken the photos in the search result. After some forth and back I ended up with a larger change (moving the loading of the photos to a new EntitySchemaDatatype).
@Lorsbyjm (or @RichardNutt ?): please do a review of my commits here as well - and point out any parts that need to be corrected, cleaned up or better documented.

**Comment by Lorsbyjm** [comment]
@sleidig what do you want to achive. Now no pictures are shown. 
Which properties do I need to set?

**Comment by sleidig** [comment]
Oh, you are absolutely right. there was another bug that converted an undefined photoFile name wrongly and broke images if you have not set up the Nextcloud integration. This should be fixed now. I also shared a test account for nextcloud in our slack in case you want to test with that as well.

**Comment by Lorsbyjm** [comment]
I do not have enough experience to review the code, but it looks like it is working.
But in the database are still children with an old entity schema, so there are no pictures shown, these children should be deletet. (To test search for Jonas)

Furthermore the loading takes even more time if for every search reslut the image is loaded from the nextcloud. We might think about limiting the search result to an special threshold and not show it if there are more. But to ask the user for more input.

**Comment by sleidig** [comment]
limiting it (maybe also just start after input of at least 3 characters) might be a good idea. The photo load should work asynchronously however - first return the path to the default image (or one that has been uploaded by the server admin) and only later replacing that if a photo is returned from the cloud.
The "Jonas" doc had an invalid photoFile path saved - probably due to the early bug.

**Pull request merged**
